const tracks=[['Midnight City','M83','cover1'],['Sunset Lover','Petit Biscuit','cover2'],['Innerbloom','RÜFÜS DU SOL','cover3'],['Electric Feel','MGMT','cover4']];
const grid=document.querySelector('#albumGrid');
function render(filter='all',query=''){
  const q=query.toLowerCase();
  grid.innerHTML=tracks.filter((t,i)=>(filter==='all'||(filter==='made'&&i<3)||(filter==='chill'&&i!==3)||(filter==='energy'&&i===3)||(filter==='focus'&&i===2))&&(!q||t.join(' ').toLowerCase().includes(q))).map((t,i)=>`<article class="album-card" data-index="${i}"><div class="album-cover ${t[2]}"></div><h3>${t[0]}</h3><p>${t[1]} · ${i%2?'Daily mix':'Made for you'}</p></article>`).join('')||'<p style="color:#9aa3ad">No results found.</p>';
  document.querySelectorAll('.album-card').forEach(card=>card.addEventListener('click',()=>playTrack(Number(card.dataset.index))));
}
function playTrack(index){const t=tracks[index];document.querySelector('#nowTitle').textContent=t[0];document.querySelector('#nowArtist').textContent=t[1];document.querySelector('#bottomTitle').textContent=t[0];document.querySelector('#nowArt').className=`now-art ${t[2]}`;document.querySelector('#playButton').textContent='Ⅱ';document.querySelector('#bottomPlay').textContent='Ⅱ';}
render();
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelector('.tab.active').classList.remove('active');tab.classList.add('active');render(tab.dataset.filter,document.querySelector('#searchInput').value)}));
document.querySelector('#searchInput').addEventListener('input',e=>render(document.querySelector('.tab.active').dataset.filter,e.target.value));
document.querySelector('#clearSearch').addEventListener('click',()=>{document.querySelector('#searchInput').value='';render(document.querySelector('.tab.active').dataset.filter)});
['#heroPlay','#playButton','#bottomPlay'].forEach(sel=>document.querySelector(sel).addEventListener('click',()=>{const buttons=[document.querySelector('#playButton'),document.querySelector('#bottomPlay')];const playing=buttons[0].textContent==='Ⅱ';buttons.forEach(b=>b.textContent=playing?'▶':'Ⅱ')}));
const chat=document.querySelector('#chatWidget');document.querySelector('#chatLauncher').addEventListener('click',()=>{chat.classList.add('open');document.querySelector('#chatLauncher').style.display='none'});document.querySelector('#minimizeChat').addEventListener('click',()=>{chat.classList.remove('open');document.querySelector('#chatLauncher').style.display='block'});
const chatBody=document.querySelector('#chatBody');const form=document.querySelector('#chatForm');const input=document.querySelector('#chatInput');function addChat(text,who='bot'){const el=document.createElement('div');el.className='chat-message';el.style.margin=who==='user'?'10px 0 10px auto':'10px 0';el.style.background=who==='user'?'#1b6338':'#252c34';el.textContent=text;chatBody.appendChild(el);chatBody.scrollTop=chatBody.scrollHeight}form.addEventListener('submit',e=>{e.preventDefault();if(!input.value.trim())return;const text=input.value.trim();addChat(text,'user');input.value='';setTimeout(()=>addChat(text.toLowerCase().includes('work')?'Let’s go! I queued a high-energy mix for your session.':'I found the perfect vibe. Try the Spotify mix above and tell me what you think ✨'),450)});document.querySelectorAll('.suggestions button').forEach(b=>b.addEventListener('click',()=>{input.value=b.textContent;form.requestSubmit()}));
const sidebar=document.querySelector('#sidebar');document.querySelector('#openMenu').addEventListener('click',()=>sidebar.classList.add('open'));document.querySelector('#closeMenu').addEventListener('click',()=>sidebar.classList.remove('open'));
